greenhouses:
   # World Name where Greenhouses will operate
   worldName:
     - world
     - creative

   # Use built-in protection? Not needed if other protection plugins are available
   useProtection: false

   # Weather and ecosystem

   # How often it should snow in the g/h when the weather is raining, in seconds
   snowspeed: 30
   # Chance of any snow falling in a greenhouse when the snow tick occurs
   # (1.0 = always, 0.0 = never)
   snowchance: 1
   # How many blocks should get snow 1 = all of them, 0 = none, 0.1 = 1 in 10
   snowdensity: 0.1

   # Biome activity
   # How often should greenhouse biomes be checked to make sure they are still valid
   ecotick: 5
   # How often should plants potentially grow in minutes if bonemeal is in the hopper
   planttick: 1
   # How often should blocks potentially convert, in minutes 
   # Example: dirt-> sand in desert greenhouse
   blocktick: 2
   # How often should mobs be potentially spawned in a greenhouse, in minutes
   mobtick: 5


   ### Default settings for greenhouse protection 

   #[true/false] PVP is allowed or denied.
   allowPvP: false
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow non-monster mobs to be hurt
   allowhurtmobs: false
   # Allow lava or water to flow out of a greenhouse, e.g. through the door, floor
   allowflowout: false
   # Allow lava or water to flow into a greenhouse, e.g., through the door
   allowflowin: false
   