greenhouses:
   # World Name where Greenhouses will operate
   worldName:
     - world
     - creative
     - ASkyBlock
     - AcidIsland

   # Console message level.
   # 0 = no messages except for warnings or severe errors
   # 1 = normal messages (default)
   # 2 and higher - debug levels - no need to use these unless you want to try debug
   debug: 1

   ### Permissions limits
   # This will limit how many greenhouses a player can make or have by permission.
   # Format is <permission>:<max number of greenhouses>
   # If max number is negative then unlimited greenhouses is allowed.
   # If a player looses a permission then the next time they log in they will
   # randomly lose greenhouses until they max out their limit.
   # If permissions are listed, only players who have them can build, except Ops.
   # The permission can be any permission you like, e.g., rank-based permission

   # Example:
   #limits:
   #  - greenhouses.player:2   <-- allows up to 2 greenhouses for default permission
   #  - greenhouses.donor:5 <-- allows up to 5 greenhouses
   #  - greenhouses.VIP:-1 <-- unlimited greenhouses
   #  - myrank.developer:100 <-- allows 100 for the permission myrank.developer

   limits:
     - greenhouses.player:5

   ### Weather and ecosystem settings

   # How often it should snow in the g/h when the weather is raining, in seconds
   snowspeed: 30
   # Chance of any snow falling in a greenhouse when the snow tick occurs
   # (1.0 = always, 0.0 = never)
   snowchance: 1
   # How many blocks should get snow 1 = all of them, 0 = none, 0.1 = 1 in 10
   snowdensity: 0.1

   # Biome activity
   # How often should greenhouse biomes be checked to make sure they are still valid
   ecotick: 5
   # How often should plants potentially grow in minutes if bonemeal is in the hopper
   planttick: 1
   # How often should blocks potentially convert, in minutes 
   # Example: dirt-> sand in desert greenhouse
   blocktick: 2
   # How often should mobs be potentially spawned in a greenhouse, in minutes
   mobtick: 5


   ### Default settings for greenhouse actions 
   # Allow lava or water to flow out of a greenhouse, e.g. through the door, floor
   allowflowout: false
   # Allow lava or water to flow into a greenhouse, e.g., through the door
   allowflowin: false
   