name: Greenhouses
main: com.wasteofplastic.greenhouses.Greenhouses
version: 1.1
description: Enables players to create biome greenhouses
author: Tastybento
depend: [Vault]
commands:
    greenhouse:
        description: Main player command
        aliases: [greenhouses, g]
        usage:  |
             /greenhouse help
    gadmin:
        description: Admin commands
        usage:  |
            /gadmin
permissions:    
  greenhouses.player:
     description: Gives access to player commands
     default: true
  greenhouses.admin:
     description: Gives access to admin commands
     default: op


